package com.example.worksyck;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class Employee {
    private String id;
    private String email;
    private String password;
    private String fullname;
    private String phone;
    private String macAddress; // Consider renaming to androidId for clarity
    private String status;
    private int companyId;
    private int departmentId;
    private int designationId;
    private String company_name;
    private String department_name;
    private String designation_name;
    private double baseSalary;
    private String salaryStructureType;
    private double normalHourRate;
    private double overtimeHourRate;
    private double regularWorkingHour; // Fixed typo
    private int workingDaysPerWeek;
    private String employee_code;
    private List<Map<String, Integer>> workingDays;
    // Constructor for minimal data (used in some parts of the app)
    public Employee(String id, String full_name, String email, String department, String company, String designation) {
        this.id = id;
        this.email = email;
        this.fullname = full_name;
        this.department_name = department;
        this.designation_name = designation;
        this.company_name = company;

    }
    // Constructor with employee_code
    public Employee(String id, String full_name, String email, String department, String company, String designation, String employee_code) {
        this(id, full_name, email, department, company, designation);
        this.employee_code = employee_code;
    }
    // Full constructor for adding new employee
    public Employee(String email, String password, String fullname, String phone, String status, int companyId,
                    int departmentId, int designationId, double baseSalary, String salaryStructureType,
                    double normalHourRate, double overtimeHourRate, double regularWorkingHour, int workingDaysPerWeek,
                    List<Map<String, Integer>>  workingDays) {
        this.id = null; // ID is generated by the database
        this.email = email;
        this.password = password;
        this.fullname = fullname;
        this.phone = phone;
        this.macAddress = null; // Set to null if not provided
        this.status = status;
        this.companyId = companyId;
        this.departmentId = departmentId;
        this.designationId = designationId;
        this.baseSalary = baseSalary;
        this.salaryStructureType = salaryStructureType;
        this.normalHourRate = normalHourRate;
        this.overtimeHourRate = overtimeHourRate;
        this.regularWorkingHour = regularWorkingHour;
        this.workingDaysPerWeek = workingDaysPerWeek;
        this.workingDays = workingDays ;
        this.employee_code = null; // Generated server-side
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMacAddress() {
        return macAddress;
    }

    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getCompanyId() {
        return companyId;
    }

    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    public int getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

    public int getDesignationId() {
        return designationId;
    }

    public void setDesignationId(int designationId) {
        this.designationId = designationId;
    }

    public String getCompany_name() {
        return company_name;
    }

    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    public String getDepartment_name() {
        return department_name;
    }

    public void setDepartment_name(String department_name) {
        this.department_name = department_name;
    }

    public String getDesignation_name() {
        return designation_name;
    }

    public void setDesignation_name(String designation_name) {
        this.designation_name = designation_name;
    }

    public double getBaseSalary() {
        return baseSalary;
    }

    public void setBaseSalary(double baseSalary) {
        this.baseSalary = baseSalary;
    }



    public String getSalaryStructureType() {
        return salaryStructureType;
    }

    public List<Map<String, Integer>> getWorkingDays() {
        return workingDays;
    }

    public void setWorkingDays(List<Map<String, Integer>> workingDays) {
        this.workingDays = workingDays;
    }

    public void setSalaryStructureType(String salaryStructureType) {
        this.salaryStructureType = salaryStructureType;
    }

    public double getNormalHourRate() {
        return normalHourRate;
    }

    public void setNormalHourRate(double normalHourRate) {
        this.normalHourRate = normalHourRate;
    }

    public double getOvertimeHourRate() {
        return overtimeHourRate;
    }

    public void setOvertimeHourRate(double overtimeHourRate) {
        this.overtimeHourRate = overtimeHourRate;
    }

    public double getRegularWorkingHour() { // Fixed method name
        return regularWorkingHour;
    }

    public void setRegularWorkingHour(double regularWorkingHour) { // Fixed method name
        this.regularWorkingHour = regularWorkingHour;
    }

    public int getWorkingDaysPerWeek() {
        return workingDaysPerWeek;
    }

    public void setWorkingDaysPerWeek(int workingDaysPerWeek) {
        this.workingDaysPerWeek = workingDaysPerWeek;
    }

    public String getEmployee_code() {
        return employee_code;
    }

    public void setEmployee_code(String employee_code) {
        this.employee_code = employee_code;
    }





}